# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afg_health_strategy', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alignment', models.TextField()),
                ('reason_alignment', models.TextField()),
                ('alignment_AFG_Health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afg_health_strategy.afghealthstrategy')),
                ('reporting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_alignment', to='reporting.reporting')),
            ],
        ),
    ]
