# Generated by Django 6.0.6 on 2026-06-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_coop', '0001_initial'),
        ('organisation_unit', '0001_initial'),
        ('technical_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_funding', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_coop.areacoop')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_coop.subareacoop')),
                ('district', models.ForeignKey(limit_choices_to={'level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='district_frameworks', to='organisation_unit.organisationunit')),
                ('region', models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='region_frameworks', to='organisation_unit.organisationunit')),
                ('technical_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_area.technicalarea')),
            ],
        ),
    ]
