# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nb_population', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('organisation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_unit.organisationunit')),
            ],
        ),
    ]
