# Generated by Django 6.0.6 on 2026-06-25 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOUIndicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_name', models.CharField()),
                ('baseline', models.FloatField()),
                ('year_one', models.IntegerField()),
                ('value_one', models.FloatField()),
                ('year_two', models.IntegerField()),
                ('value_two', models.FloatField()),
                ('year_three', models.IntegerField()),
                ('value_three', models.FloatField()),
                ('year_four', models.IntegerField()),
                ('value_four', models.FloatField()),
                ('year_five', models.IntegerField()),
                ('value_five', models.FloatField()),
            ],
        ),
    ]
