# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='YearIndicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MOUIndicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('indicator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.indicators')),
                ('year_indicators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.yearindicators')),
            ],
        ),
    ]
