# Generated by Django 6.0.6 on 2026-06-25 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou_indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_name', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='mouindicators',
            name='indicator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.indicators'),
        ),
    ]
