# Generated by Django 6.0.6 on 2026-06-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework_funding', '0001_initial'),
        ('ip_identifier', '0001_initial'),
        ('monitoring_technical_performance', '0001_initial'),
        ('qualitative_analysis', '0001_initial'),
        ('risk_matrix', '0001_initial'),
        ('strategic_alignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework_funding.frameworkfunding')),
                ('ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_identifier.ipidentifier')),
                ('monitoring_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_technical_performance.monitoringalignment')),
                ('qualitative_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitative_analysis.qualitativeanalysis')),
                ('risk_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_matrix.riskmatrixactionplan')),
                ('strategic_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategic_alignment.strategicalignment')),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportingperiod')),
            ],
        ),
    ]
