# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip_identifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_identifier.ipidentifier')),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportingperiod')),
            ],
        ),
    ]
