# Generated by Django 6.0.6 on 2026-06-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualitativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interventions_key_success', models.TextField()),
                ('interventions_bottleneck_factors', models.TextField()),
            ],
        ),
    ]
