# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interventions_key_success', models.TextField()),
                ('interventions_bottleneck_factors', models.TextField()),
                ('reporting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_analysis', to='reporting.reporting')),
            ],
        ),
    ]
