# Generated by Django 6.0.6 on 2026-06-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_source', '0001_initial'),
        ('mou_indicators', '0001_initial'),
        ('sens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_target', models.FloatField(default=0)),
                ('result_achieved', models.FloatField(default=0)),
                ('achievement_rate', models.FloatField(default=0)),
                ('performance_status', models.FloatField(default=0)),
                ('total_population_covered', models.PositiveIntegerField(default=0)),
                ('total_population_reached', models.PositiveIntegerField(default=0)),
                ('total_population_covered_female', models.PositiveIntegerField(default=0)),
                ('total_population_reached_male', models.PositiveIntegerField(default=0)),
                ('data_source_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_source.datasourceindicator')),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.mouindicators')),
                ('sens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sens.sens')),
            ],
        ),
    ]
