# Generated by Django 6.0.6 on 2026-06-27 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_source', '0001_initial'),
        ('mou_indicators', '0001_initial'),
        ('reporting', '0001_initial'),
        ('sens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_target', models.FloatField(default=0)),
                ('result_achieved', models.FloatField(default=0)),
                ('achievement_rate', models.FloatField(default=0)),
                ('performance_status', models.FloatField(default=0)),
                ('total_population_covered', models.PositiveIntegerField(default=0)),
                ('total_population_reached', models.PositiveIntegerField(default=0)),
                ('total_population_covered_female', models.PositiveIntegerField(default=0)),
                ('total_population_reached_male', models.PositiveIntegerField(default=0)),
                ('data_source_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_source.datasourceindicator')),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.indicators')),
                ('reporting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alignment', to='reporting.reporting')),
                ('sens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sens.sens')),
            ],
        ),
    ]
