# Generated by Django 6.0.6 on 2026-06-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_technical_performance', '0001_initial'),
        ('mou_indicators', '0002_indicators_alter_mouindicators_indicator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringalignment',
            name='performance_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mou_indicators.indicators'),
        ),
    ]
