# Generated by Django 6.0.6 on 2026-06-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMatrixActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_identified', models.TextField()),
                ('impact', models.PositiveIntegerField()),
                ('probability', models.PositiveIntegerField()),
                ('risk_score', models.PositiveIntegerField()),
                ('risk_level', models.CharField()),
                ('measure_mitigation_proposed', models.CharField()),
                ('main_responsible', models.CharField()),
                ('due_date', models.DateField()),
                ('action_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_status.actionstatus')),
            ],
        ),
    ]
