# Generated by Django 6.0.6 on 2026-06-25 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_name', models.CharField(max_length=50)),
                ('activity_name', models.TextField()),
                ('description', models.TextField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget', models.IntegerField()),
                ('donor', models.CharField(max_length=50)),
                ('version', models.DateField()),
            ],
        ),
    ]
